spring:
  application:
    name: PesoWise-Server

  datasource:
    url: jdbc:postgresql://209.46.126.200:5432/pesowise_db
    username: dev_pesowise
    password: 1yNh66^m9
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: edson.john.cruz.domingo@gmail.com
    password: oyotpkncfyhxyaku
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


secret:
  key: hQm4Khsf0pjIx8RNrg3LTbrbCsiiW6V78iyiaF1k4wg=
  baseUrl: http://localhost:8080
  jwtKey: Cbf9iP65ogrWZhBI6Tevdc4XAySdNJaCSBxd2M8XDzk=

#server:
#  address: 127.0.0.1

#logging:
#  level:
#    org:
#      springframework: DEBUG
