spring:
  application:
    name: PesoWise-Server

  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    url: jdbc:postgresql://209.46.126.200:5432/pesowise_db
    username: dev_pesowise
    password: 314u6Hi$i
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.ionos.com
    port: 587
    username: sales@gopesowise.com
    password: Darkhunter23#
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


secret:
  key: hQm4Khsf0pjIx8RNrg3LTbrbCsiiW6V78iyiaF1k4wg=
  baseUrl: http://localhost:8080
  jwtKey: Cbf9iP65ogrWZhBI6Tevdc4XAySdNJaCSBxd2M8XDzk=

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.web.filter.CorsFilter: DEBUG
#server:
#  address: 127.0.0.1

#logging:
#  level:
#    org:
#      springframework: DEBUG
